### ISSUE TITLE
Enable CORS for Amazon S3 bucket?

### ISSUE THREAD

**Issue by cmdcolin** [genome-in-a-bottle/giab_latest_release#10]
Hi there,
I work with a web based genome browsers and being able to access remote resources is a great way to demo our tool, but generally we can only access resources that have CORS enabled.

Would it be possible to enable CORS on the S3 bucket?

I have found that these CORS settings worked well with S3

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin><!-- insert your origin here --></AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>Range</AllowedHeader>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>Accept-Ranges</ExposeHeader>
        <ExposeHeader>Content-Range</ExposeHeader>
        <ExposeHeader>Content-Encoding</ExposeHeader>
        <ExposeHeader>Content-Length</ExposeHeader>
        <AllowedHeader>Authorization</AllowedHeader>
    </CORSRule>
</CORSConfiguration>

```

**Comment by cmdcolin** [comment]
Probably * for AllowedOrigin :)

**Comment by jzook** [comment]
Thanks for reporting this.  Could you submit this as an issue to AWS, since
they would have control over this, here (
https://github.com/awslabs/open-data-registry/issues)?  You might also be
able to use the NCBI GIAB ftp files under
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/ if you replace ftp: with https:

Cheers,
Justin

**Comment by cmdcolin** [comment]
Thanks for the recommendation. That makes sense. I'll close for now
