### ISSUE TITLE
HighConf VCF entries outside of HighConf BED file

### ISSUE THREAD

**Issue by mozack** [genome-in-a-bottle/giab_latest_release#2]
Hi,

I am seeing some entries in:
HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf.vcf.gz

that appear to not be within the regions defined in:
HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf.bed

Is this expected?

Running the following command results in >70,000 filtered records:
rtg-tools-3.7/rtg vcffilter --include-bed HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf.bed -i HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf.vcf.gz -o hg38.giab.filtered.vcf.gz

Total records : 3619471
**_Filtered due to include file : 76168_**
Remaining records : 3543303

Here is an example variant that appears to be outside of the bed file ranges:

chr22	19096624	.	AG	A	50	PASS	platforms=3;platformnames=Illumina,CG,10X;datasets=3;datasetnames=HiSeqPE300x,CGnormal,10XChromium;callsets=3;callsetnames=HiSeqPE300xGATK,CGnormal,10XGATKhaplo;datasetsmissingcall=HiSeqPE300x,IonExome,SolidPE50x50bp,SolidSE75bp;callable=CS_HiSeqPE300xGATK_callable,CS_CGnormal_callable,CS_HiSeqPE300xfreebayes_callable;filt=CS_CGnormal_filt,CS_HiSeqPE300xfreebayes_filt,CS_10XGATKhaplo_filt,CS_SolidSE75GATKHC_filt;arbitrated=TRUE	GT:PS:DP:ADALL:AD:GQ	0|1:19096624_AG_A:319:137,138:120,126:396

Clarification on this would be appreciated.

Thanks!

**Comment by elowy01** [comment]
Hi, 
I was about to ask the same,

I've identified some variants in HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf.vcf.gz that are not in the region defined by HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf.bed.

Is this expected?

Thanks,

ernesto

**Comment by jzook** [comment]
Hi all,

Yes, we include sites outside the bed file in the vcf because it enables more robust benchmarking of variant calls.  In particular, around complex variants where part of the variant could be inside the bed file and part of the variant could be outside the bed file, depending on how it is represented, including these sites in the vcf allows different representations of the same variant to be compared properly in more cases.  Benchmarking tools such as those developed by GA4GH will exclude the sites outside the bed from counts of TP, FP, and FN after doing the comparison (see example with hap.py here - https://github.com/ga4gh/benchmarking-tools/blob/master/resources/high-confidence-sets/giab.md)

Cheers,
Justin Zook
NIST

**Comment by Talo07** [comment]
Hi,

I just noticed the same thing. Is it normal to have a different number between TRUTH.TOTAL and TRUTH.TP? I would like to make a correct comparison between the vcf file of HG001_GRCh38_GIAB_highconf and my query.vcf  file and I would like to have the same number between TRUTH.TOTAL and TRUTH.TP so that I can compare my results well.

Do you have any ideas ??

**Comment by jzook** [comment]
In general TRUTH.TP<TRUTH.TOTAL unless the query callset has 100% recall/sensitivity. TRUTH.TP contains only the variants  that the query vcf matches.  These fields are defined in tables in https://rdcu.be/bqpDT and at https://github.com/Illumina/hap.py/blob/master/doc/happy.md
